services:
  ollama:
    init: true
    container_name: ollama
    build:
      context: .
      dockerfile: Dockerfile
    image: "jcsmith08/ollama"
    ports:
      - "11434:11434"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
